import { ResourceState } from '../types/economy.types';
import { EventBus } from './EventBus';
import {
  BASE_GOLD_PER_SEC,
  GOLD_TICK_INTERVAL,
} from '../constants/balance.constants';
import { World } from '../world/World';
import { RotationPhysicsSystem } from './RotationPhysicsSystem';
import {
  miningOutput,
  researcherOutput,
  converterOutput,
  healerOutput,
  healerRadius,
  gearRadius,
} from '../constants/gear.constants';
import { UnitSystem } from './UnitSystem';
import { distance } from '../utils/MathUtils';

/**
 * Manages gold, iron, crystal, and aether for both player and AI.
 * Gold: passive income, spent on gear placement and unit spawning
 * Iron/Crystal/Aether: generated by mining gear full-rotations only
 * No longer manages power resource.
 */
export class EconomySystem {
  private eventBus: EventBus;
  private world: World;
  private rotationPhysics!: RotationPhysicsSystem;
  private unitSystem: UnitSystem | null = null;

  private playerResources: ResourceState = {
    gold: 30, iron: 0, crystal: 0, aether: 0,
  };
  private aiResources: ResourceState = {
    gold: 30, iron: 0, crystal: 0, aether: 0,
  };

  private playerGoldBonusPerSec: number = 0;
  private aiGoldBonusPerSec: number = 0;

  private lastGoldTick: number = 0;
  private practiceMode: boolean = false;

  private readonly onGearFullRotation = ({ gearId, owner }: { gearId: string; owner: 'player' | 'ai' }) => {
    const gear = this.world.getGear(gearId);
    if (!gear) return;

    if (gear.type === 'iron_miner') {
      const amt = miningOutput(gear.teeth);
      this.earnResource(owner, 'iron', amt);
      this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+${amt.toFixed(1)} iron`, color: 0xcc9966 });
    } else if (gear.type === 'crystal_miner') {
      const amt = miningOutput(gear.teeth);
      this.earnResource(owner, 'crystal', amt);
      this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+${amt.toFixed(1)} crystal`, color: 0x66ccff });
    } else if (gear.type === 'aether_miner') {
      const amt = miningOutput(gear.teeth);
      this.earnResource(owner, 'aether', amt);
      this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+${amt.toFixed(1)} aether`, color: 0xcc66ff });

    } else if (gear.type === 'researcher') {
      const amount = researcherOutput(gear.teeth);
      this.eventBus.emit('gear:research_boost', { owner, amount });
      this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+${(amount / 1000).toFixed(1)}s research`, color: 0x88ffee });

    } else if (gear.type === 'iron_converter') {
      const amt = converterOutput(gear.teeth);
      const res = owner === 'player' ? this.playerResources : this.aiResources;
      if (res.iron >= amt) {
        this.spendResource(owner, 'iron', amt);
        const goldGained = amt * 2;
        this.earnGold(owner, goldGained);
        this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+${goldGained.toFixed(1)}g`, color: 0xffdd44 });
      }
    } else if (gear.type === 'crystal_converter') {
      const amt = converterOutput(gear.teeth);
      const res = owner === 'player' ? this.playerResources : this.aiResources;
      if (res.crystal >= amt) {
        this.spendResource(owner, 'crystal', amt);
        const goldGained = amt * 3;
        this.earnGold(owner, goldGained);
        this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+${goldGained.toFixed(1)}g`, color: 0xffdd44 });
      }
    } else if (gear.type === 'aether_converter') {
      const amt = converterOutput(gear.teeth);
      const res = owner === 'player' ? this.playerResources : this.aiResources;
      if (res.aether >= amt) {
        this.spendResource(owner, 'aether', amt);
        const goldGained = amt * 6;
        this.earnGold(owner, goldGained);
        this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+${goldGained.toFixed(1)}g`, color: 0xffdd44 });
      }

    } else if (gear.type === 'armored') {
      // Heal on spin (costs gold)
      const healAmt = Math.max(1, gear.teeth * 0.3);
      const goldCost = Math.max(1, Math.round(gear.teeth * 0.1));
      if (this.canAffordGold(owner, goldCost)) {
        this.spendGold(owner, goldCost);
        gear.hp = Math.min(gear.maxHp, gear.hp + healAmt);
        this.world.updateGear(gear);
        this.eventBus.emit('gear:rotation_result', { gearId: gear.id, owner, text: `+${healAmt.toFixed(1)} HP`, color: 0x44ff88 });
      }

    } else if (gear.type === 'spiked') {
      // Tiny heal on spin (no gold cost)
      const healAmt = Math.max(0.5, gear.teeth * 0.1);
      gear.hp = Math.min(gear.maxHp, gear.hp + healAmt);
      this.world.updateGear(gear);
      this.eventBus.emit('gear:rotation_result', { gearId: gear.id, owner, text: `+${healAmt.toFixed(1)} HP`, color: 0x88ff44 });

    } else if (gear.type === 'healer') {
      // Heal nearby friendly gears and units
      const healAmt = healerOutput(gear.teeth);
      const radius = healerRadius(gear.teeth);

      // Heal nearby friendly gears
      for (const [, otherGear] of this.world.getAllGears()) {
        if (otherGear.id === gear.id) continue;
        if (otherGear.owner !== owner) continue;
        const d = distance(gear.x, gear.y, otherGear.x, otherGear.y);
        if (d <= radius + gearRadius(otherGear.teeth)) {
          otherGear.hp = Math.min(otherGear.maxHp, otherGear.hp + healAmt);
          this.world.updateGear(otherGear);
        }
      }

      // Heal nearby friendly units
      if (this.unitSystem) {
        for (const [, unit] of this.unitSystem.getAllUnits()) {
          if (unit.owner !== owner) continue;
          const d = distance(gear.x, gear.y, unit.x, unit.y);
          if (d <= radius) {
            unit.hp = Math.min(unit.maxHp, unit.hp + healAmt);
          }
        }
      }

      this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+${healAmt.toFixed(1)} heal`, color: 0x44ff88 });
      this.eventBus.emit('gear:healer_pulse', { gearId, x: gear.x, y: gear.y, radius, owner });

    } else if (gear.type === 'crossbow_turret') {
      // Buy 1 ammo (2 gold)
      const ammoCost = 2;
      const maxAmmo = gear.maxAmmo ?? 3;
      const currentAmmo = gear.ammo ?? 0;
      if (currentAmmo < maxAmmo && this.canAffordGold(owner, ammoCost)) {
        this.spendGold(owner, ammoCost);
        gear.ammo = currentAmmo + 1;
        this.world.updateGear(gear);
        this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+1 ammo (${gear.ammo}/${maxAmmo})`, color: 0xffdd00 });
      } else if (currentAmmo >= maxAmmo) {
        this.eventBus.emit('gear:rotation_result', { gearId, owner, text: 'AMMO FULL', color: 0xffaa00 });
      }
    } else if (gear.type === 'artillery_turret') {
      // Buy 1 ammo shell (6 gold)
      const ammoCost = 6;
      const maxAmmo = gear.maxAmmo ?? 3;
      const currentAmmo = gear.ammo ?? 0;
      if (currentAmmo < maxAmmo && this.canAffordGold(owner, ammoCost)) {
        this.spendGold(owner, ammoCost);
        gear.ammo = currentAmmo + 1;
        this.world.updateGear(gear);
        this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+1 shell (${gear.ammo}/${maxAmmo})`, color: 0xff6600 });
      } else if (currentAmmo >= maxAmmo) {
        this.eventBus.emit('gear:rotation_result', { gearId, owner, text: 'AMMO FULL', color: 0xff8800 });
      }
    } else if (gear.type === 'minelayer') {
      // Buy 1 mine shell (5 gold)
      const ammoCost = 5;
      const maxAmmo = gear.maxAmmo ?? 3;
      const currentAmmo = gear.ammo ?? 0;
      if (currentAmmo < maxAmmo && this.canAffordGold(owner, ammoCost)) {
        this.spendGold(owner, ammoCost);
        gear.ammo = currentAmmo + 1;
        this.world.updateGear(gear);
        this.eventBus.emit('gear:rotation_result', { gearId, owner, text: `+1 mine (${gear.ammo}/${maxAmmo})`, color: 0xff4488 });
      } else if (currentAmmo >= maxAmmo) {
        this.eventBus.emit('gear:rotation_result', { gearId, owner, text: 'AMMO FULL', color: 0xff4488 });
      }
    }
  };

  private readonly onEconomySpendGold = ({ owner, amount }: { owner: 'player' | 'ai'; amount: number }) => {
    this.spendGold(owner, amount);
  };

  constructor(eventBus: EventBus, world: World) {
    this.eventBus = eventBus;
    this.world = world;

    this.eventBus.on('gear:full_rotation', this.onGearFullRotation);
    this.eventBus.on('economy:spend_gold', this.onEconomySpendGold);
  }

  setRotationPhysics(rps: RotationPhysicsSystem): void {
    this.rotationPhysics = rps;
  }

  setUnitSystem(us: UnitSystem): void {
    this.unitSystem = us;
  }

  /** In practice mode the AI has effectively infinite resources. */
  setPracticeMode(enabled: boolean): void {
    this.practiceMode = enabled;
    if (enabled) {
      // Pre-fill AI with a huge starting pool
      this.aiResources = { gold: 999999, iron: 999999, crystal: 999999, aether: 999999 };
    }
  }

  update(now: number): void {
    if (now - this.lastGoldTick >= GOLD_TICK_INTERVAL) {
      this.lastGoldTick = now;
      this.tickGold();
    }
  }

  private tickGold(): void {
    const playerGoldGain = BASE_GOLD_PER_SEC + this.playerGoldBonusPerSec;
    this.earnGold('player', playerGoldGain);

    if (this.practiceMode) {
      // Keep AI resources pinned to a huge value — effectively infinite
      this.aiResources = { gold: 999999, iron: 999999, crystal: 999999, aether: 999999 };
    } else {
      const aiGoldGain = BASE_GOLD_PER_SEC + this.aiGoldBonusPerSec;
      this.earnGold('ai', aiGoldGain);
    }
  }

  earnGold(owner: 'player' | 'ai', amount: number): void {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    res.gold += amount;
    this.eventBus.emit('economy:gold_changed', { owner, resources: { ...res } });
  }

  spendGold(owner: 'player' | 'ai', amount: number): boolean {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    if (res.gold < amount) {
      this.eventBus.emit('economy:insufficient_funds', { owner, resource: 'gold', needed: amount });
      return false;
    }
    res.gold -= amount;
    this.eventBus.emit('economy:gold_changed', { owner, resources: { ...res } });
    return true;
  }

  canAffordGold(owner: 'player' | 'ai', amount: number): boolean {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    return res.gold >= amount;
  }

  earnResource(owner: 'player' | 'ai', type: 'iron' | 'crystal' | 'aether', amount: number): void {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    res[type] += amount;
    this.eventBus.emit('economy:resources_changed', { owner, resources: { ...res } });
  }

  spendResource(owner: 'player' | 'ai', type: 'iron' | 'crystal' | 'aether', amount: number): boolean {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    if (res[type] < amount) {
      this.eventBus.emit('economy:insufficient_funds', { owner, resource: type, needed: amount });
      return false;
    }
    res[type] -= amount;
    this.eventBus.emit('economy:resources_changed', { owner, resources: { ...res } });
    return true;
  }

  canAffordResource(owner: 'player' | 'ai', type: 'iron' | 'crystal' | 'aether', amount: number): boolean {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    return res[type] >= amount;
  }

  getResources(owner: 'player' | 'ai'): ResourceState {
    return owner === 'player' ? { ...this.playerResources } : { ...this.aiResources };
  }

  applyGoldBonus(owner: 'player' | 'ai', bonusPerSec: number): void {
    if (owner === 'player') this.playerGoldBonusPerSec += bonusPerSec;
    else this.aiGoldBonusPerSec += bonusPerSec;
  }

  destroy(): void {
    this.eventBus.off('gear:full_rotation', this.onGearFullRotation);
    this.eventBus.off('economy:spend_gold', this.onEconomySpendGold);
  }
}
