import { ResourceState } from '../types/economy.types';
import type { GearState } from '../types/gear.types';
import { GEAR_BEHAVIOURS } from '../gears/registry';
import type { GearBehaviourCtx, StockResource } from '../gears/types';
import { tierPower } from '../constants/tier.constants';
import { EventBus } from './EventBus';
import {
  BASE_GOLD_PER_SEC,
  GOLD_TICK_INTERVAL,
} from '../constants/balance.constants';
import { World } from '../world/World';
import { UnitSystem } from './UnitSystem';

/** Window for the HUD's trailing resource-rate tooltip. */
const RATE_WINDOW_MS = 60000;

/**
 * Manages gold, iron, crystal, and aether for both player and AI.
 * Gold: passive income, spent on gear placement and unit spawning
 * Iron/Crystal/Aether: generated by mining gear full-rotations only
 * No longer manages power resource.
 */
export class EconomySystem {
  private eventBus: EventBus;
  private world: World;
  private unitSystem: UnitSystem | null = null;

  private playerResources: ResourceState = {
    gold: 30, iron: 0, crystal: 0, aether: 0, coal: 0,
  };
  private aiResources: ResourceState = {
    gold: 30, iron: 0, crystal: 0, aether: 0, coal: 0,
  };

  private playerGoldBonusPerSec: number = 0;
  private aiGoldBonusPerSec: number = 0;

  private lastGoldTick: number = 0;
  private practiceMode: boolean = false;
  private now: number = 0;

  /** Rolling per-resource, per-owner samples of organic (non-purchase) net
   * change, used to compute the HUD's trailing-average rate tooltip. Manual
   * purchases (gear placement/sale, research spend/refund, ability use) are
   * deliberately not recorded here -- the tooltip answers "what is my machine
   * doing for me," not "what did I just spend." */
  private rateSamples: Record<'player' | 'ai', Record<keyof ResourceState, Array<{ t: number; delta: number }>>> = {
    player: { gold: [], iron: [], crystal: [], aether: [], coal: [] },
    ai: { gold: [], iron: [], crystal: [], aether: [], coal: [] },
  };

  /**
   * Every completed rotation pays out through the gear behaviour registry.
   *
   * This used to be a 150-line `if (gear.type === ...)` chain. It is now a
   * lookup, because the chain was the reason a new gear type had to be
   * threaded through five systems by hand -- and the reason two spawners once
   * shipped completely inert.
   */
  private readonly onGearFullRotation = ({ gearId, owner }: { gearId: string; owner: 'player' | 'ai' }) => {
    const gear = this.world.getGear(gearId);
    if (!gear) return;

    // Raider-disabled: this rotation produces nothing at all, regardless of
    // gear type. The gear keeps spinning (and still costs the chain its
    // reflected inertia) -- it just doesn't pay out.
    if (gear.disabledUntil && this.now < gear.disabledUntil) {
      this.eventBus.emit('gear:rotation_result', { gearId, owner, text: 'RAIDED', color: 0xff4444 });
      return;
    }

    GEAR_BEHAVIOURS[gear.type].onRotation?.(this.behaviourCtx(gear, owner));
  };

  /**
   * Build the narrow context a behaviour runs against. Behaviours never see a
   * system class, so they stay unit-testable against a hand-built fake.
   */
  behaviourCtx(gear: GearState, owner: 'player' | 'ai'): GearBehaviourCtx {
    return {
      gear,
      owner,
      tier: gear.tier,
      power: tierPower(gear.tier),
      now: this.now,
      world: this.world,
      economy: this,
      units: this.unitSystem,
      emit: (event, payload) => this.eventBus.emit(event, payload),
      report: (text, color) =>
        this.eventBus.emit('gear:rotation_result', { gearId: gear.id, owner, text, color }),
    };
  }

  private readonly onEconomySpendGold = ({ owner, amount }: { owner: 'player' | 'ai'; amount: number }) => {
    this.spendGold(owner, amount);
  };

  constructor(eventBus: EventBus, world: World) {
    this.eventBus = eventBus;
    this.world = world;

    this.eventBus.on('gear:full_rotation', this.onGearFullRotation);
    this.eventBus.on('economy:spend_gold', this.onEconomySpendGold);
  }


  setUnitSystem(us: UnitSystem): void {
    this.unitSystem = us;
  }

  /** In practice mode the AI has effectively infinite resources. */
  setPracticeMode(enabled: boolean): void {
    this.practiceMode = enabled;
    if (enabled) {
      // Pre-fill AI with a huge starting pool
      this.aiResources = { gold: 999999, iron: 999999, crystal: 999999, aether: 999999, coal: 999999 };
    }
  }

  update(now: number): void {
    this.now = now;
    if (now - this.lastGoldTick >= GOLD_TICK_INTERVAL) {
      this.lastGoldTick = now;
      this.tickGold();
    }
    this.pruneRateSamples(now);
  }

  private pruneRateSamples(now: number): void {
    for (const owner of ['player', 'ai'] as const) {
      for (const key of ['gold', 'iron', 'crystal', 'aether'] as const) {
        const samples = this.rateSamples[owner][key];
        while (samples.length > 0 && now - samples[0].t > RATE_WINDOW_MS) samples.shift();
      }
    }
  }

  private recordSample(owner: 'player' | 'ai', key: keyof ResourceState, delta: number): void {
    this.rateSamples[owner][key].push({ t: this.now, delta });
  }

  /**
   * Trailing average rate of organic change (per second) for a resource,
   * over the last RATE_WINDOW_MS -- or since match start if shorter.
   * Excludes manual purchases (see rateSamples doc comment above).
   */
  getRate(owner: 'player' | 'ai', key: keyof ResourceState): number {
    const samples = this.rateSamples[owner][key];
    if (samples.length === 0) return 0;
    const total = samples.reduce((sum, s) => sum + s.delta, 0);
    const windowMs = Math.max(1000, Math.min(RATE_WINDOW_MS, this.now));
    return total / (windowMs / 1000);
  }

  private tickGold(): void {
    const playerGoldGain = BASE_GOLD_PER_SEC + this.playerGoldBonusPerSec;
    this.earnGold('player', playerGoldGain);

    if (this.practiceMode) {
      // Keep AI resources pinned to a huge value — effectively infinite
      this.aiResources = { gold: 999999, iron: 999999, crystal: 999999, aether: 999999, coal: 999999 };
    } else {
      const aiGoldGain = BASE_GOLD_PER_SEC + this.aiGoldBonusPerSec;
      this.earnGold('ai', aiGoldGain);
    }
  }

  earnGold(owner: 'player' | 'ai', amount: number, trackForRate: boolean = true): void {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    res.gold += amount;
    if (trackForRate) this.recordSample(owner, 'gold', amount);
    this.eventBus.emit('economy:gold_changed', { owner, resources: { ...res } });
  }

  spendGold(owner: 'player' | 'ai', amount: number, trackForRate: boolean = true): boolean {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    if (res.gold < amount) {
      this.eventBus.emit('economy:insufficient_funds', { owner, resource: 'gold', needed: amount });
      return false;
    }
    res.gold -= amount;
    if (trackForRate) this.recordSample(owner, 'gold', -amount);
    this.eventBus.emit('economy:gold_changed', { owner, resources: { ...res } });
    return true;
  }

  canAffordGold(owner: 'player' | 'ai', amount: number): boolean {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    return res.gold >= amount;
  }

  earnResource(owner: 'player' | 'ai', type: StockResource, amount: number, trackForRate: boolean = true): void {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    res[type] += amount;
    if (trackForRate) this.recordSample(owner, type, amount);
    this.eventBus.emit('economy:resources_changed', { owner, resources: { ...res } });
  }

  spendResource(owner: 'player' | 'ai', type: StockResource, amount: number, trackForRate: boolean = true): boolean {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    if (res[type] < amount) {
      this.eventBus.emit('economy:insufficient_funds', { owner, resource: type, needed: amount });
      return false;
    }
    res[type] -= amount;
    if (trackForRate) this.recordSample(owner, type, -amount);
    this.eventBus.emit('economy:resources_changed', { owner, resources: { ...res } });
    return true;
  }

  canAffordResource(owner: 'player' | 'ai', type: StockResource, amount: number): boolean {
    const res = owner === 'player' ? this.playerResources : this.aiResources;
    return res[type] >= amount;
  }

  getResources(owner: 'player' | 'ai'): ResourceState {
    return owner === 'player' ? { ...this.playerResources } : { ...this.aiResources };
  }

  applyGoldBonus(owner: 'player' | 'ai', bonusPerSec: number): void {
    if (owner === 'player') this.playerGoldBonusPerSec += bonusPerSec;
    else this.aiGoldBonusPerSec += bonusPerSec;
  }

  /** Passive gold/sec this side currently earns (base rate + researched/gear bonuses). */
  getGoldPerSec(owner: 'player' | 'ai'): number {
    return BASE_GOLD_PER_SEC + (owner === 'player' ? this.playerGoldBonusPerSec : this.aiGoldBonusPerSec);
  }

  destroy(): void {
    this.eventBus.off('gear:full_rotation', this.onGearFullRotation);
    this.eventBus.off('economy:spend_gold', this.onEconomySpendGold);
  }
}
